version: 2
updates:
  - package-ecosystem: npm
    directory: /werkzeuge
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /vorlage
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
